config/routes.rb
Screencaster::Application.routes.draw do
  resources :episodes do
    collection do
      put :update_many
    end
  end
  match 'new', to: 'episodes#new'
  root to: 'episodes#index'
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  attr_accessible :description, :name, :seconds, :published_on, :timecode
  validates_presence_of :name, :description
  scope :published, where('published_on <= ?', Time.now.to_date)

  has_paper_trail

  def timecode
    if seconds
      min, sec = *seconds.divmod(60)
      [min, sec.to_s.rjust(2, '0')].join(':')
    end
  end

  def timecode=(timecode)
    if timecode.present?
      min, sec = *timecode.split(':').map(&:to_i)
      self.seconds = min*60 + sec
    end
  end

  def minutes
    (seconds/60.0).round if seconds
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_filter :load_episode, only: [:show, :edit, :update, :destroy]
  caches_page :index

  def index
    @episodes = Episode.published.find_all_by_pro(false)
  end

  def show
  end

  def new
    @episode = Episode.new
  end

  def edit
  end

  def create
    @episode = Episode.new(params[:episode])
    if @episode.save
      redirect_to @episode, notice: 'Episode was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    if @episode.update_attributes(params[:episode])
      redirect_to @episode, notice: 'Episode was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @episode.destroy
    redirect_to episodes_url, notice: 'Episode was successfully destroyed.'
  end

private

  def load_episode
    @episode = Episode.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.erb
<%= form_for(@episode) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :timecode, "Duration (timecode)" %><br />
    <%= f.number_field :timecode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<h1>Listing episodes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Seconds</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @episodes.each do |episode| %>
  <tr>
    <td><%= episode.name %></td>
    <td><%= episode.description %></td>
    <td><%= episode.seconds %></td>
    <td><%= link_to 'Show', episode %></td>
    <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
    <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render 'form' %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<p>
  <b>Name:</b>
  <%= @episode.name %>
</p>

<p>
  <b>Description:</b>
  <%= @episode.description %>
</p>

<p>
  <b>Duration:</b>
  <%= pluralize @episode.minutes, "minute" %>
</p>

<% if @episode.published_on %>
<p>
  <b>Published on:</b>
  <%= @episode.published_on.strftime("%B %e, %Y") %>
</p>
<% end %>


<%= link_to 'Edit', edit_episode_path(@episode) %> |
<%= link_to 'Destroy', @episode, method: :delete %> |
<%= link_to 'Back', episodes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Example</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>